In [3]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [4]:
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')

X=dataset.iloc[:,:4].values
y = dataset['species'].values
print(dataset.head(5))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [6]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size = 0.2)

In [8]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [10]:
y_pred = classifier.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix 
cm =confusion_matrix(y_test, y_pred) 
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(y_test,y_pred))
print(cm)

Accuracy :  0.9666666666666667
[[ 9  0  0]
 [ 0 12  0]
 [ 0  1  8]]


In [13]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
print(df)

   Real Values Predicted Values
0   versicolor       versicolor
1    virginica        virginica
2   versicolor       versicolor
3    virginica        virginica
4    virginica       versicolor
5       setosa           setosa
6   versicolor       versicolor
7       setosa           setosa
8   versicolor       versicolor
9    virginica        virginica
10      setosa           setosa
11      setosa           setosa
12   virginica        virginica
13      setosa           setosa
14   virginica        virginica
15  versicolor       versicolor
16  versicolor       versicolor
17      setosa           setosa
18   virginica        virginica
19   virginica        virginica
20  versicolor       versicolor
21  versicolor       versicolor
22  versicolor       versicolor
23  versicolor       versicolor
24   virginica        virginica
25  versicolor       versicolor
26      setosa           setosa
27      setosa           setosa
28  versicolor       versicolor
29      setosa           setosa


In [14]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

In [16]:
m=accuracy_score(y_test, y_pred)
print("error rate:-",1-m)

error rate:- 0.033333333333333326


In [17]:
print('Precision:',precision_score(y_test,y_pred,average='micro'))

Precision: 0.9666666666666667


In [18]:
print("Recall Score:",recall_score(y_test,y_pred,average='micro'))

Recall Score: 0.9666666666666667
